import type { LicenseCategory } from './CategoryTypes'

export interface ReportItemType {
  id: string
  name: string
  click: () => void
  show:boolean
}

export interface Report1Type {
  'ID Number': string
  Name: string
  Address: string
  Categories: LicenseCategory[]
  Cars: string[]
}
export interface Report2Type {
  'Plate Number': string
  Brand: string
  'Seat Amount': number
  'Available KM': number
}
// Generated by https://quicktype.io

export interface Report3Type {
  Date: string
  'Program type': string
  'Car number': string
  'Driver name': string
  'Copilot name': null
  'Group number': number
  'Group country': string
  'Tourist amount': number
  'Start time': string
  'Program description': string
}

export interface Report4Type {
  date: string
  plate_number: string
  situation_name: string
  return_date?: string
}

export interface Report5Type {
  date: string
  name: string
  situation_name: string
  return_date?: string
}

export interface Report6Type {
  id_number: string
  name: string
  plate_number: string
  brand: string
}

export interface Report7Type {
  id_number: string
  name: string
  plate_number: string
  brand: string
}

export interface Report8Type {
  id_number: string
  name: string
  plate_number: string
  brand: string
}

export interface Report9Type {
  id_number: string
  name: string
  plate_number: string
  brand: string
}
